version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: marquei-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1937
      POSTGRES_DB: marquei
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - marquei-network

  redis:
    image: redis:7-alpine
    container_name: marquei-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - marquei-network
    command: redis-server --appendonly yes

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  marquei-network:
    driver: bridge
